### ISSUE TITLE
can dashboard support sofaboot-dependencies:3.2.2/dashboard可以支持sofaboot 3.2.2版本吗

### ISSUE THREAD

**Issue by Charles19961002** [sofastack/sofa-dashboard-client#34]
我自行打包且提高了dashboard-client-sofa-boot-starter的parent依赖，从3.1.4到3.2.2。解决了AppPublisher不同版本下的package不同问题，但是当我引入依赖，运行项目的时候会报一些异常，以下是其中一个。不过放在3.1.4版本下是可以正常运行的，希望同学能帮忙排除，升级dashboard-client-sofa-boot-starter到3.2.2可用。

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method org.apache.curator.framework.CuratorFramework.newWatcherRemoveCuratorFramework()Lorg/apache/curator/framework/WatcherRemoveCuratorFramework; but it does not exist. Its class, org.apache.curator.framework.CuratorFramework, is available from the following locations:

    jar:file:/Users/didi/workspace/sofastack-dashboard-guides/guides-dashboard-ark-master/target/guides-dashboard-ark-master-1.0.0-executable-ark.jar!/SOFA-ARK/biz/guides-dashboard-ark-master-1.0.0-ark-biz.jar!/lib/curator-framework-2.9.1.jar!/org/apache/curator/framework/CuratorFramework.class

It was loaded from the following location:

    jar:file:/Users/didi/workspace/sofastack-dashboard-guides/guides-dashboard-ark-master/target/guides-dashboard-ark-master-1.0.0-executable-ark.jar!/SOFA-ARK/biz/guides-dashboard-ark-master-1.0.0-ark-biz.jar!/lib/curator-framework-2.9.1.jar!/

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.curator.framework.CuratorFramework

2020-09-09 14:13:38.194  INFO 17284 --- [main] .l.SofaDashboardContextRefreshedListener : sofa dashboard client unregister failed.

org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /apps/instance/ark-master/127.0.0.1:8088?internalHost=null&startTime=1599632015510&lastRecover=1599632015510&state=UP
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:242) ~[curator-framework-2.9.1.jar!/:na]
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:236) ~[curator-framework-2.9.1.jar!/:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[curator-client-2.9.1.jar!/:na]
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:232) ~[curator-framework-2.9.1.jar!/:na]
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:217) ~[curator-framework-2.9.1.jar!/:na]
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:41) ~[curator-framework-2.9.1.jar!/:na]
	at com.alipay.sofa.dashboard.client.registry.zookeeper.ZookeeperAppPublisher.unRegister(ZookeeperAppPublisher.java:115) ~[dashboard-client-core-1.1.0-SNAPSHOT.jar!/:1.1.0-SNAPSHOT]
	at com.alipay.sofa.dashboard.client.listener.SofaDashboardContextClosedListener.onApplicationEvent(SofaDashboardContextClosedListener.java:40) [dashboard-client-sofa-boot-starter-1.1.0-SNAPSHOT.jar!/:1.1.0-SNAPSHOT]
	at com.alipay.sofa.dashboard.client.listener.SofaDashboardContextClosedListener.onApplicationEvent(SofaDashboardContextClosedListener.java:31) [dashboard-client-sofa-boot-starter-1.1.0-SNAPSHOT.jar!/:1.1.0-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:994) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961) [spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:834) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at io.sofastack.ark.master.MasterApplication.main(MasterApplication.java:13) [guides-dashboard-ark-master-1.0.0-ark-biz.jar!/:1.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) [sofa-ark-archive-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:207) [sofa-ark-container-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.service.biz.DefaultBizDeployer.deploy(DefaultBizDeployer.java:52) [sofa-ark-container-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.service.biz.BizDeployServiceImpl.deploy(BizDeployServiceImpl.java:55) [sofa-ark-container-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.pipeline.DeployBizStage.process(DeployBizStage.java:47) [sofa-ark-container-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.pipeline.StandardPipeline.process(StandardPipeline.java:75) [sofa-ark-container-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.ArkContainer.start(ArkContainer.java:135) [sofa-ark-container-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.container.ArkContainer.main(ArkContainer.java:91) [sofa-ark-container-0.6.0.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) [sofa-ark-archive-0.6.0.jar!/:na]
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:97) [guides-dashboard-ark-master-1.0.0-executable-ark.jar:1.0.0]
	at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:49) [guides-dashboard-ark-master-1.0.0-executable-ark.jar:1.0.0]
	at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35) [guides-dashboard-ark-master-1.0.0-executable-ark.jar:1.0.0]

**Comment by Charles19961002** [comment]
我使用的demo是https://github.com/sofastack-guides/sofastack-dashboard-guides
